sonar.projectKey=Stradivary_koperasi-kegelapan-app
sonar.organization=stradivary
sonar.projectName=koperasi-kegelapan

# Sources & tests
sonar.sources=src,api/src
sonar.exclusions=\
  src/routeTree.gen.ts,\
  src/db/**,\
  src/presentation/components/ui/**,\
  src/infrastructure/persistence/dexie/indexeddb.ts,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/__tests__/**,\
  **/scripts/**,\
  scripts/**,\
  scripts/migration-manifest.json,\
  api/src/application/index.ts,\
  api/src/domain/index.ts,\
  src/test-setup.ts,\
  src/integrations/**,\
  src/assets/**

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=\
  src/presentation/routes/**,\
  src/main.tsx,\
  src/routeTree.gen.ts,\
  src/presentation/components/ui/**,\
  src/test-setup.ts,\
  **/scripts/**,\
  scripts/**,\
  scripts/migration-manifest.json,\
  api/src/application/index.ts,\
  api/src/domain/index.ts,\
  src/db/**,\
  src/infrastructure/persistence/dexie/indexeddb.ts,\
  **/__tests__/**,\
  **/__mocks__/**,\
  src/integrations/**,\
  src/assets/**,\
  src/cloudflare-env.d.ts,\
  src/styles.css

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8