/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantTenantIdRouteImport } from './routes/tenant.$tenantId'
import { Route as ApiSessionGrantRouteImport } from './routes/api/session-grant'
import { Route as ApiReconcileRouteImport } from './routes/api/reconcile'
import { Route as ApiPolicyRouteImport } from './routes/api/policy'
import { Route as ApiCardsRouteImport } from './routes/api/cards'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as TenantTenantIdTerminalRouteImport } from './routes/tenant.$tenantId.terminal'
import { Route as TenantTenantIdStationRouteImport } from './routes/tenant.$tenantId.station'
import { Route as TenantTenantIdScoutRouteImport } from './routes/tenant.$tenantId.scout'
import { Route as TenantTenantIdKioskRouteImport } from './routes/tenant.$tenantId.kiosk'
import { Route as TenantTenantIdGateRouteImport } from './routes/tenant.$tenantId.gate'
import { Route as TenantTenantIdAdminRouteImport } from './routes/tenant.$tenantId.admin'
import { Route as ApiCardsCardIdRouteImport } from './routes/api/cards.$cardId'
import { Route as ApiAuthTokenRouteImport } from './routes/api/auth/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantTenantIdRoute = TenantTenantIdRouteImport.update({
  id: '/tenant/$tenantId',
  path: '/tenant/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionGrantRoute = ApiSessionGrantRouteImport.update({
  id: '/api/session-grant',
  path: '/api/session-grant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReconcileRoute = ApiReconcileRouteImport.update({
  id: '/api/reconcile',
  path: '/api/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolicyRoute = ApiPolicyRouteImport.update({
  id: '/api/policy',
  path: '/api/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsRoute = ApiCardsRouteImport.update({
  id: '/api/cards',
  path: '/api/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantTenantIdTerminalRoute = TenantTenantIdTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdStationRoute = TenantTenantIdStationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdScoutRoute = TenantTenantIdScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdKioskRoute = TenantTenantIdKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdGateRoute = TenantTenantIdGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdAdminRoute = TenantTenantIdAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const ApiCardsCardIdRoute = ApiCardsCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => ApiCardsRoute,
} as any)
const ApiAuthTokenRoute = ApiAuthTokenRouteImport.update({
  id: '/api/auth/token',
  path: '/api/auth/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/cards': typeof ApiCardsRouteWithChildren
  '/api/policy': typeof ApiPolicyRoute
  '/api/reconcile': typeof ApiReconcileRoute
  '/api/session-grant': typeof ApiSessionGrantRoute
  '/tenant/$tenantId': typeof TenantTenantIdRouteWithChildren
  '/api/auth/token': typeof ApiAuthTokenRoute
  '/api/cards/$cardId': typeof ApiCardsCardIdRoute
  '/tenant/$tenantId/admin': typeof TenantTenantIdAdminRoute
  '/tenant/$tenantId/gate': typeof TenantTenantIdGateRoute
  '/tenant/$tenantId/kiosk': typeof TenantTenantIdKioskRoute
  '/tenant/$tenantId/scout': typeof TenantTenantIdScoutRoute
  '/tenant/$tenantId/station': typeof TenantTenantIdStationRoute
  '/tenant/$tenantId/terminal': typeof TenantTenantIdTerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/cards': typeof ApiCardsRouteWithChildren
  '/api/policy': typeof ApiPolicyRoute
  '/api/reconcile': typeof ApiReconcileRoute
  '/api/session-grant': typeof ApiSessionGrantRoute
  '/tenant/$tenantId': typeof TenantTenantIdRouteWithChildren
  '/api/auth/token': typeof ApiAuthTokenRoute
  '/api/cards/$cardId': typeof ApiCardsCardIdRoute
  '/tenant/$tenantId/admin': typeof TenantTenantIdAdminRoute
  '/tenant/$tenantId/gate': typeof TenantTenantIdGateRoute
  '/tenant/$tenantId/kiosk': typeof TenantTenantIdKioskRoute
  '/tenant/$tenantId/scout': typeof TenantTenantIdScoutRoute
  '/tenant/$tenantId/station': typeof TenantTenantIdStationRoute
  '/tenant/$tenantId/terminal': typeof TenantTenantIdTerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/cards': typeof ApiCardsRouteWithChildren
  '/api/policy': typeof ApiPolicyRoute
  '/api/reconcile': typeof ApiReconcileRoute
  '/api/session-grant': typeof ApiSessionGrantRoute
  '/tenant/$tenantId': typeof TenantTenantIdRouteWithChildren
  '/api/auth/token': typeof ApiAuthTokenRoute
  '/api/cards/$cardId': typeof ApiCardsCardIdRoute
  '/tenant/$tenantId/admin': typeof TenantTenantIdAdminRoute
  '/tenant/$tenantId/gate': typeof TenantTenantIdGateRoute
  '/tenant/$tenantId/kiosk': typeof TenantTenantIdKioskRoute
  '/tenant/$tenantId/scout': typeof TenantTenantIdScoutRoute
  '/tenant/$tenantId/station': typeof TenantTenantIdStationRoute
  '/tenant/$tenantId/terminal': typeof TenantTenantIdTerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/audit'
    | '/api/cards'
    | '/api/policy'
    | '/api/reconcile'
    | '/api/session-grant'
    | '/tenant/$tenantId'
    | '/api/auth/token'
    | '/api/cards/$cardId'
    | '/tenant/$tenantId/admin'
    | '/tenant/$tenantId/gate'
    | '/tenant/$tenantId/kiosk'
    | '/tenant/$tenantId/scout'
    | '/tenant/$tenantId/station'
    | '/tenant/$tenantId/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/audit'
    | '/api/cards'
    | '/api/policy'
    | '/api/reconcile'
    | '/api/session-grant'
    | '/tenant/$tenantId'
    | '/api/auth/token'
    | '/api/cards/$cardId'
    | '/tenant/$tenantId/admin'
    | '/tenant/$tenantId/gate'
    | '/tenant/$tenantId/kiosk'
    | '/tenant/$tenantId/scout'
    | '/tenant/$tenantId/station'
    | '/tenant/$tenantId/terminal'
  id:
    | '__root__'
    | '/'
    | '/api/audit'
    | '/api/cards'
    | '/api/policy'
    | '/api/reconcile'
    | '/api/session-grant'
    | '/tenant/$tenantId'
    | '/api/auth/token'
    | '/api/cards/$cardId'
    | '/tenant/$tenantId/admin'
    | '/tenant/$tenantId/gate'
    | '/tenant/$tenantId/kiosk'
    | '/tenant/$tenantId/scout'
    | '/tenant/$tenantId/station'
    | '/tenant/$tenantId/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuditRoute: typeof ApiAuditRoute
  ApiCardsRoute: typeof ApiCardsRouteWithChildren
  ApiPolicyRoute: typeof ApiPolicyRoute
  ApiReconcileRoute: typeof ApiReconcileRoute
  ApiSessionGrantRoute: typeof ApiSessionGrantRoute
  TenantTenantIdRoute: typeof TenantTenantIdRouteWithChildren
  ApiAuthTokenRoute: typeof ApiAuthTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/$tenantId': {
      id: '/tenant/$tenantId'
      path: '/tenant/$tenantId'
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof TenantTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-grant': {
      id: '/api/session-grant'
      path: '/api/session-grant'
      fullPath: '/api/session-grant'
      preLoaderRoute: typeof ApiSessionGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reconcile': {
      id: '/api/reconcile'
      path: '/api/reconcile'
      fullPath: '/api/reconcile'
      preLoaderRoute: typeof ApiReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policy': {
      id: '/api/policy'
      path: '/api/policy'
      fullPath: '/api/policy'
      preLoaderRoute: typeof ApiPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards': {
      id: '/api/cards'
      path: '/api/cards'
      fullPath: '/api/cards'
      preLoaderRoute: typeof ApiCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/$tenantId/terminal': {
      id: '/tenant/$tenantId/terminal'
      path: '/terminal'
      fullPath: '/tenant/$tenantId/terminal'
      preLoaderRoute: typeof TenantTenantIdTerminalRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/station': {
      id: '/tenant/$tenantId/station'
      path: '/station'
      fullPath: '/tenant/$tenantId/station'
      preLoaderRoute: typeof TenantTenantIdStationRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/scout': {
      id: '/tenant/$tenantId/scout'
      path: '/scout'
      fullPath: '/tenant/$tenantId/scout'
      preLoaderRoute: typeof TenantTenantIdScoutRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/kiosk': {
      id: '/tenant/$tenantId/kiosk'
      path: '/kiosk'
      fullPath: '/tenant/$tenantId/kiosk'
      preLoaderRoute: typeof TenantTenantIdKioskRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/gate': {
      id: '/tenant/$tenantId/gate'
      path: '/gate'
      fullPath: '/tenant/$tenantId/gate'
      preLoaderRoute: typeof TenantTenantIdGateRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/admin': {
      id: '/tenant/$tenantId/admin'
      path: '/admin'
      fullPath: '/tenant/$tenantId/admin'
      preLoaderRoute: typeof TenantTenantIdAdminRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/api/cards/$cardId': {
      id: '/api/cards/$cardId'
      path: '/$cardId'
      fullPath: '/api/cards/$cardId'
      preLoaderRoute: typeof ApiCardsCardIdRouteImport
      parentRoute: typeof ApiCardsRoute
    }
    '/api/auth/token': {
      id: '/api/auth/token'
      path: '/api/auth/token'
      fullPath: '/api/auth/token'
      preLoaderRoute: typeof ApiAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiCardsRouteChildren {
  ApiCardsCardIdRoute: typeof ApiCardsCardIdRoute
}

const ApiCardsRouteChildren: ApiCardsRouteChildren = {
  ApiCardsCardIdRoute: ApiCardsCardIdRoute,
}

const ApiCardsRouteWithChildren = ApiCardsRoute._addFileChildren(
  ApiCardsRouteChildren,
)

interface TenantTenantIdRouteChildren {
  TenantTenantIdAdminRoute: typeof TenantTenantIdAdminRoute
  TenantTenantIdGateRoute: typeof TenantTenantIdGateRoute
  TenantTenantIdKioskRoute: typeof TenantTenantIdKioskRoute
  TenantTenantIdScoutRoute: typeof TenantTenantIdScoutRoute
  TenantTenantIdStationRoute: typeof TenantTenantIdStationRoute
  TenantTenantIdTerminalRoute: typeof TenantTenantIdTerminalRoute
}

const TenantTenantIdRouteChildren: TenantTenantIdRouteChildren = {
  TenantTenantIdAdminRoute: TenantTenantIdAdminRoute,
  TenantTenantIdGateRoute: TenantTenantIdGateRoute,
  TenantTenantIdKioskRoute: TenantTenantIdKioskRoute,
  TenantTenantIdScoutRoute: TenantTenantIdScoutRoute,
  TenantTenantIdStationRoute: TenantTenantIdStationRoute,
  TenantTenantIdTerminalRoute: TenantTenantIdTerminalRoute,
}

const TenantTenantIdRouteWithChildren = TenantTenantIdRoute._addFileChildren(
  TenantTenantIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuditRoute: ApiAuditRoute,
  ApiCardsRoute: ApiCardsRouteWithChildren,
  ApiPolicyRoute: ApiPolicyRoute,
  ApiReconcileRoute: ApiReconcileRoute,
  ApiSessionGrantRoute: ApiSessionGrantRoute,
  TenantTenantIdRoute: TenantTenantIdRouteWithChildren,
  ApiAuthTokenRoute: ApiAuthTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
