/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './presentation/routes/__root'
import { Route as SuperadminRouteImport } from './presentation/routes/superadmin'
import { Route as DevicesRouteImport } from './presentation/routes/devices'
import { Route as IndexRouteImport } from './presentation/routes/index'
import { Route as DevIndexRouteImport } from './presentation/routes/dev.index'
import { Route as TenantTenantIdRouteImport } from './presentation/routes/tenant.$tenantId'
import { Route as DevNfcTestRouteImport } from './presentation/routes/dev.nfc-test'
import { Route as DevIssuanceTestRouteImport } from './presentation/routes/dev.issuance-test'
import { Route as TenantTenantIdAdminRouteImport } from './presentation/routes/tenant.$tenantId.admin'
import { Route as TenantTenantIdKioskLayoutRouteImport } from './presentation/routes/tenant.$tenantId._kioskLayout'
import { Route as TenantTenantIdAdminLayoutRouteImport } from './presentation/routes/tenant.$tenantId._adminLayout'
import { Route as TenantTenantIdKioskLayoutTerminalRouteImport } from './presentation/routes/tenant.$tenantId._kioskLayout.terminal'
import { Route as TenantTenantIdKioskLayoutScoutRouteImport } from './presentation/routes/tenant.$tenantId._kioskLayout.scout'
import { Route as TenantTenantIdKioskLayoutGateRouteImport } from './presentation/routes/tenant.$tenantId._kioskLayout.gate'
import { Route as TenantTenantIdAdminLayoutTransactionsRouteImport } from './presentation/routes/tenant.$tenantId._adminLayout.transactions'
import { Route as TenantTenantIdAdminLayoutSettingsRouteImport } from './presentation/routes/tenant.$tenantId._adminLayout.settings'
import { Route as TenantTenantIdAdminLayoutMembersRouteImport } from './presentation/routes/tenant.$tenantId._adminLayout.members'
import { Route as TenantTenantIdAdminLayoutCardsRouteImport } from './presentation/routes/tenant.$tenantId._adminLayout.cards'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantTenantIdRoute = TenantTenantIdRouteImport.update({
  id: '/tenant/$tenantId',
  path: '/tenant/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevNfcTestRoute = DevNfcTestRouteImport.update({
  id: '/dev/nfc-test',
  path: '/dev/nfc-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIssuanceTestRoute = DevIssuanceTestRouteImport.update({
  id: '/dev/issuance-test',
  path: '/dev/issuance-test',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantTenantIdAdminRoute = TenantTenantIdAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdKioskLayoutRoute =
  TenantTenantIdKioskLayoutRouteImport.update({
    id: '/_kioskLayout',
    getParentRoute: () => TenantTenantIdRoute,
  } as any)
const TenantTenantIdAdminLayoutRoute =
  TenantTenantIdAdminLayoutRouteImport.update({
    id: '/_adminLayout',
    getParentRoute: () => TenantTenantIdRoute,
  } as any)
const TenantTenantIdKioskLayoutTerminalRoute =
  TenantTenantIdKioskLayoutTerminalRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => TenantTenantIdKioskLayoutRoute,
  } as any)
const TenantTenantIdKioskLayoutScoutRoute =
  TenantTenantIdKioskLayoutScoutRouteImport.update({
    id: '/scout',
    path: '/scout',
    getParentRoute: () => TenantTenantIdKioskLayoutRoute,
  } as any)
const TenantTenantIdKioskLayoutGateRoute =
  TenantTenantIdKioskLayoutGateRouteImport.update({
    id: '/gate',
    path: '/gate',
    getParentRoute: () => TenantTenantIdKioskLayoutRoute,
  } as any)
const TenantTenantIdAdminLayoutTransactionsRoute =
  TenantTenantIdAdminLayoutTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => TenantTenantIdAdminLayoutRoute,
  } as any)
const TenantTenantIdAdminLayoutSettingsRoute =
  TenantTenantIdAdminLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => TenantTenantIdAdminLayoutRoute,
  } as any)
const TenantTenantIdAdminLayoutMembersRoute =
  TenantTenantIdAdminLayoutMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => TenantTenantIdAdminLayoutRoute,
  } as any)
const TenantTenantIdAdminLayoutCardsRoute =
  TenantTenantIdAdminLayoutCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => TenantTenantIdAdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/superadmin': typeof SuperadminRoute
  '/dev/issuance-test': typeof DevIssuanceTestRoute
  '/dev/nfc-test': typeof DevNfcTestRoute
  '/tenant/$tenantId': typeof TenantTenantIdRouteWithChildren
  '/dev/': typeof DevIndexRoute
  '/tenant/$tenantId/admin': typeof TenantTenantIdAdminRoute
  '/tenant/$tenantId/cards': typeof TenantTenantIdAdminLayoutCardsRoute
  '/tenant/$tenantId/members': typeof TenantTenantIdAdminLayoutMembersRoute
  '/tenant/$tenantId/settings': typeof TenantTenantIdAdminLayoutSettingsRoute
  '/tenant/$tenantId/transactions': typeof TenantTenantIdAdminLayoutTransactionsRoute
  '/tenant/$tenantId/gate': typeof TenantTenantIdKioskLayoutGateRoute
  '/tenant/$tenantId/scout': typeof TenantTenantIdKioskLayoutScoutRoute
  '/tenant/$tenantId/terminal': typeof TenantTenantIdKioskLayoutTerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/superadmin': typeof SuperadminRoute
  '/dev/issuance-test': typeof DevIssuanceTestRoute
  '/dev/nfc-test': typeof DevNfcTestRoute
  '/tenant/$tenantId': typeof TenantTenantIdRouteWithChildren
  '/dev': typeof DevIndexRoute
  '/tenant/$tenantId/admin': typeof TenantTenantIdAdminRoute
  '/tenant/$tenantId/cards': typeof TenantTenantIdAdminLayoutCardsRoute
  '/tenant/$tenantId/members': typeof TenantTenantIdAdminLayoutMembersRoute
  '/tenant/$tenantId/settings': typeof TenantTenantIdAdminLayoutSettingsRoute
  '/tenant/$tenantId/transactions': typeof TenantTenantIdAdminLayoutTransactionsRoute
  '/tenant/$tenantId/gate': typeof TenantTenantIdKioskLayoutGateRoute
  '/tenant/$tenantId/scout': typeof TenantTenantIdKioskLayoutScoutRoute
  '/tenant/$tenantId/terminal': typeof TenantTenantIdKioskLayoutTerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/superadmin': typeof SuperadminRoute
  '/dev/issuance-test': typeof DevIssuanceTestRoute
  '/dev/nfc-test': typeof DevNfcTestRoute
  '/tenant/$tenantId': typeof TenantTenantIdRouteWithChildren
  '/dev/': typeof DevIndexRoute
  '/tenant/$tenantId/_adminLayout': typeof TenantTenantIdAdminLayoutRouteWithChildren
  '/tenant/$tenantId/_kioskLayout': typeof TenantTenantIdKioskLayoutRouteWithChildren
  '/tenant/$tenantId/admin': typeof TenantTenantIdAdminRoute
  '/tenant/$tenantId/_adminLayout/cards': typeof TenantTenantIdAdminLayoutCardsRoute
  '/tenant/$tenantId/_adminLayout/members': typeof TenantTenantIdAdminLayoutMembersRoute
  '/tenant/$tenantId/_adminLayout/settings': typeof TenantTenantIdAdminLayoutSettingsRoute
  '/tenant/$tenantId/_adminLayout/transactions': typeof TenantTenantIdAdminLayoutTransactionsRoute
  '/tenant/$tenantId/_kioskLayout/gate': typeof TenantTenantIdKioskLayoutGateRoute
  '/tenant/$tenantId/_kioskLayout/scout': typeof TenantTenantIdKioskLayoutScoutRoute
  '/tenant/$tenantId/_kioskLayout/terminal': typeof TenantTenantIdKioskLayoutTerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/superadmin'
    | '/dev/issuance-test'
    | '/dev/nfc-test'
    | '/tenant/$tenantId'
    | '/dev/'
    | '/tenant/$tenantId/admin'
    | '/tenant/$tenantId/cards'
    | '/tenant/$tenantId/members'
    | '/tenant/$tenantId/settings'
    | '/tenant/$tenantId/transactions'
    | '/tenant/$tenantId/gate'
    | '/tenant/$tenantId/scout'
    | '/tenant/$tenantId/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices'
    | '/superadmin'
    | '/dev/issuance-test'
    | '/dev/nfc-test'
    | '/tenant/$tenantId'
    | '/dev'
    | '/tenant/$tenantId/admin'
    | '/tenant/$tenantId/cards'
    | '/tenant/$tenantId/members'
    | '/tenant/$tenantId/settings'
    | '/tenant/$tenantId/transactions'
    | '/tenant/$tenantId/gate'
    | '/tenant/$tenantId/scout'
    | '/tenant/$tenantId/terminal'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/superadmin'
    | '/dev/issuance-test'
    | '/dev/nfc-test'
    | '/tenant/$tenantId'
    | '/dev/'
    | '/tenant/$tenantId/_adminLayout'
    | '/tenant/$tenantId/_kioskLayout'
    | '/tenant/$tenantId/admin'
    | '/tenant/$tenantId/_adminLayout/cards'
    | '/tenant/$tenantId/_adminLayout/members'
    | '/tenant/$tenantId/_adminLayout/settings'
    | '/tenant/$tenantId/_adminLayout/transactions'
    | '/tenant/$tenantId/_kioskLayout/gate'
    | '/tenant/$tenantId/_kioskLayout/scout'
    | '/tenant/$tenantId/_kioskLayout/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRoute
  SuperadminRoute: typeof SuperadminRoute
  DevIssuanceTestRoute: typeof DevIssuanceTestRoute
  DevNfcTestRoute: typeof DevNfcTestRoute
  TenantTenantIdRoute: typeof TenantTenantIdRouteWithChildren
  DevIndexRoute: typeof DevIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/$tenantId': {
      id: '/tenant/$tenantId'
      path: '/tenant/$tenantId'
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof TenantTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/nfc-test': {
      id: '/dev/nfc-test'
      path: '/dev/nfc-test'
      fullPath: '/dev/nfc-test'
      preLoaderRoute: typeof DevNfcTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/issuance-test': {
      id: '/dev/issuance-test'
      path: '/dev/issuance-test'
      fullPath: '/dev/issuance-test'
      preLoaderRoute: typeof DevIssuanceTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/$tenantId/admin': {
      id: '/tenant/$tenantId/admin'
      path: '/admin'
      fullPath: '/tenant/$tenantId/admin'
      preLoaderRoute: typeof TenantTenantIdAdminRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/_kioskLayout': {
      id: '/tenant/$tenantId/_kioskLayout'
      path: ''
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof TenantTenantIdKioskLayoutRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/_adminLayout': {
      id: '/tenant/$tenantId/_adminLayout'
      path: ''
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof TenantTenantIdAdminLayoutRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/_kioskLayout/terminal': {
      id: '/tenant/$tenantId/_kioskLayout/terminal'
      path: '/terminal'
      fullPath: '/tenant/$tenantId/terminal'
      preLoaderRoute: typeof TenantTenantIdKioskLayoutTerminalRouteImport
      parentRoute: typeof TenantTenantIdKioskLayoutRoute
    }
    '/tenant/$tenantId/_kioskLayout/scout': {
      id: '/tenant/$tenantId/_kioskLayout/scout'
      path: '/scout'
      fullPath: '/tenant/$tenantId/scout'
      preLoaderRoute: typeof TenantTenantIdKioskLayoutScoutRouteImport
      parentRoute: typeof TenantTenantIdKioskLayoutRoute
    }
    '/tenant/$tenantId/_kioskLayout/gate': {
      id: '/tenant/$tenantId/_kioskLayout/gate'
      path: '/gate'
      fullPath: '/tenant/$tenantId/gate'
      preLoaderRoute: typeof TenantTenantIdKioskLayoutGateRouteImport
      parentRoute: typeof TenantTenantIdKioskLayoutRoute
    }
    '/tenant/$tenantId/_adminLayout/transactions': {
      id: '/tenant/$tenantId/_adminLayout/transactions'
      path: '/transactions'
      fullPath: '/tenant/$tenantId/transactions'
      preLoaderRoute: typeof TenantTenantIdAdminLayoutTransactionsRouteImport
      parentRoute: typeof TenantTenantIdAdminLayoutRoute
    }
    '/tenant/$tenantId/_adminLayout/settings': {
      id: '/tenant/$tenantId/_adminLayout/settings'
      path: '/settings'
      fullPath: '/tenant/$tenantId/settings'
      preLoaderRoute: typeof TenantTenantIdAdminLayoutSettingsRouteImport
      parentRoute: typeof TenantTenantIdAdminLayoutRoute
    }
    '/tenant/$tenantId/_adminLayout/members': {
      id: '/tenant/$tenantId/_adminLayout/members'
      path: '/members'
      fullPath: '/tenant/$tenantId/members'
      preLoaderRoute: typeof TenantTenantIdAdminLayoutMembersRouteImport
      parentRoute: typeof TenantTenantIdAdminLayoutRoute
    }
    '/tenant/$tenantId/_adminLayout/cards': {
      id: '/tenant/$tenantId/_adminLayout/cards'
      path: '/cards'
      fullPath: '/tenant/$tenantId/cards'
      preLoaderRoute: typeof TenantTenantIdAdminLayoutCardsRouteImport
      parentRoute: typeof TenantTenantIdAdminLayoutRoute
    }
  }
}

interface TenantTenantIdAdminLayoutRouteChildren {
  TenantTenantIdAdminLayoutCardsRoute: typeof TenantTenantIdAdminLayoutCardsRoute
  TenantTenantIdAdminLayoutMembersRoute: typeof TenantTenantIdAdminLayoutMembersRoute
  TenantTenantIdAdminLayoutSettingsRoute: typeof TenantTenantIdAdminLayoutSettingsRoute
  TenantTenantIdAdminLayoutTransactionsRoute: typeof TenantTenantIdAdminLayoutTransactionsRoute
}

const TenantTenantIdAdminLayoutRouteChildren: TenantTenantIdAdminLayoutRouteChildren =
  {
    TenantTenantIdAdminLayoutCardsRoute: TenantTenantIdAdminLayoutCardsRoute,
    TenantTenantIdAdminLayoutMembersRoute:
      TenantTenantIdAdminLayoutMembersRoute,
    TenantTenantIdAdminLayoutSettingsRoute:
      TenantTenantIdAdminLayoutSettingsRoute,
    TenantTenantIdAdminLayoutTransactionsRoute:
      TenantTenantIdAdminLayoutTransactionsRoute,
  }

const TenantTenantIdAdminLayoutRouteWithChildren =
  TenantTenantIdAdminLayoutRoute._addFileChildren(
    TenantTenantIdAdminLayoutRouteChildren,
  )

interface TenantTenantIdKioskLayoutRouteChildren {
  TenantTenantIdKioskLayoutGateRoute: typeof TenantTenantIdKioskLayoutGateRoute
  TenantTenantIdKioskLayoutScoutRoute: typeof TenantTenantIdKioskLayoutScoutRoute
  TenantTenantIdKioskLayoutTerminalRoute: typeof TenantTenantIdKioskLayoutTerminalRoute
}

const TenantTenantIdKioskLayoutRouteChildren: TenantTenantIdKioskLayoutRouteChildren =
  {
    TenantTenantIdKioskLayoutGateRoute: TenantTenantIdKioskLayoutGateRoute,
    TenantTenantIdKioskLayoutScoutRoute: TenantTenantIdKioskLayoutScoutRoute,
    TenantTenantIdKioskLayoutTerminalRoute:
      TenantTenantIdKioskLayoutTerminalRoute,
  }

const TenantTenantIdKioskLayoutRouteWithChildren =
  TenantTenantIdKioskLayoutRoute._addFileChildren(
    TenantTenantIdKioskLayoutRouteChildren,
  )

interface TenantTenantIdRouteChildren {
  TenantTenantIdAdminLayoutRoute: typeof TenantTenantIdAdminLayoutRouteWithChildren
  TenantTenantIdKioskLayoutRoute: typeof TenantTenantIdKioskLayoutRouteWithChildren
  TenantTenantIdAdminRoute: typeof TenantTenantIdAdminRoute
}

const TenantTenantIdRouteChildren: TenantTenantIdRouteChildren = {
  TenantTenantIdAdminLayoutRoute: TenantTenantIdAdminLayoutRouteWithChildren,
  TenantTenantIdKioskLayoutRoute: TenantTenantIdKioskLayoutRouteWithChildren,
  TenantTenantIdAdminRoute: TenantTenantIdAdminRoute,
}

const TenantTenantIdRouteWithChildren = TenantTenantIdRoute._addFileChildren(
  TenantTenantIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRoute,
  SuperadminRoute: SuperadminRoute,
  DevIssuanceTestRoute: DevIssuanceTestRoute,
  DevNfcTestRoute: DevNfcTestRoute,
  TenantTenantIdRoute: TenantTenantIdRouteWithChildren,
  DevIndexRoute: DevIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
