/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TerminalStationRouteImport } from './routes/terminal/station'
import { Route as TerminalScoutRouteImport } from './routes/terminal/scout'
import { Route as TerminalGateRouteImport } from './routes/terminal/gate'
import { Route as TerminalExitRouteImport } from './routes/terminal/exit'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTerminalsRouteImport } from './routes/admin/terminals'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminMembersActivityRouteImport } from './routes/admin/members_.activity'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalStationRoute = TerminalStationRouteImport.update({
  id: '/terminal/station',
  path: '/terminal/station',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalScoutRoute = TerminalScoutRouteImport.update({
  id: '/terminal/scout',
  path: '/terminal/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalGateRoute = TerminalGateRouteImport.update({
  id: '/terminal/gate',
  path: '/terminal/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalExitRoute = TerminalExitRouteImport.update({
  id: '/terminal/exit',
  path: '/terminal/exit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTerminalsRoute = AdminTerminalsRouteImport.update({
  id: '/admin/terminals',
  path: '/admin/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersActivityRoute = AdminMembersActivityRouteImport.update({
  id: '/admin/members_/activity',
  path: '/admin/members/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/terminal/exit': typeof TerminalExitRoute
  '/terminal/gate': typeof TerminalGateRoute
  '/terminal/scout': typeof TerminalScoutRoute
  '/terminal/station': typeof TerminalStationRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members/activity': typeof AdminMembersActivityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/terminal/exit': typeof TerminalExitRoute
  '/terminal/gate': typeof TerminalGateRoute
  '/terminal/scout': typeof TerminalScoutRoute
  '/terminal/station': typeof TerminalStationRoute
  '/admin': typeof AdminIndexRoute
  '/admin/members/activity': typeof AdminMembersActivityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/terminal/exit': typeof TerminalExitRoute
  '/terminal/gate': typeof TerminalGateRoute
  '/terminal/scout': typeof TerminalScoutRoute
  '/terminal/station': typeof TerminalStationRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members_/activity': typeof AdminMembersActivityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/config'
    | '/admin/members'
    | '/admin/terminals'
    | '/admin/users'
    | '/terminal/exit'
    | '/terminal/gate'
    | '/terminal/scout'
    | '/terminal/station'
    | '/admin/'
    | '/admin/members/activity'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/config'
    | '/admin/members'
    | '/admin/terminals'
    | '/admin/users'
    | '/terminal/exit'
    | '/terminal/gate'
    | '/terminal/scout'
    | '/terminal/station'
    | '/admin'
    | '/admin/members/activity'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/config'
    | '/admin/members'
    | '/admin/terminals'
    | '/admin/users'
    | '/terminal/exit'
    | '/terminal/gate'
    | '/terminal/scout'
    | '/terminal/station'
    | '/admin/'
    | '/admin/members_/activity'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminTerminalsRoute: typeof AdminTerminalsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  TerminalExitRoute: typeof TerminalExitRoute
  TerminalGateRoute: typeof TerminalGateRoute
  TerminalScoutRoute: typeof TerminalScoutRoute
  TerminalStationRoute: typeof TerminalStationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMembersActivityRoute: typeof AdminMembersActivityRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/station': {
      id: '/terminal/station'
      path: '/terminal/station'
      fullPath: '/terminal/station'
      preLoaderRoute: typeof TerminalStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/scout': {
      id: '/terminal/scout'
      path: '/terminal/scout'
      fullPath: '/terminal/scout'
      preLoaderRoute: typeof TerminalScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/gate': {
      id: '/terminal/gate'
      path: '/terminal/gate'
      fullPath: '/terminal/gate'
      preLoaderRoute: typeof TerminalGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/exit': {
      id: '/terminal/exit'
      path: '/terminal/exit'
      fullPath: '/terminal/exit'
      preLoaderRoute: typeof TerminalExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/terminals': {
      id: '/admin/terminals'
      path: '/admin/terminals'
      fullPath: '/admin/terminals'
      preLoaderRoute: typeof AdminTerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members_/activity': {
      id: '/admin/members_/activity'
      path: '/admin/members/activity'
      fullPath: '/admin/members/activity'
      preLoaderRoute: typeof AdminMembersActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminTerminalsRoute: AdminTerminalsRoute,
  AdminUsersRoute: AdminUsersRoute,
  TerminalExitRoute: TerminalExitRoute,
  TerminalGateRoute: TerminalGateRoute,
  TerminalScoutRoute: TerminalScoutRoute,
  TerminalStationRoute: TerminalStationRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMembersActivityRoute: AdminMembersActivityRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
